Create a mapping from header files to labels that define them.
The format is:
```
bar.h //:bar(//:first_toolchain) //:bar(//:second_toolchain)
foo.h //:foo
```

The purpose of this is to allow a custom clang plugin to rewrite error
messages from:
foo.h:1:10: module "//:foo_Private" does not depend on a module exporting 'bar.h'
#include "bar.h"
          ^

to:
path/to/foo.h:1:10: error: //foo:foo does not directly depend on //:bar, which contains 'bar.h' in its public deps
#include "path/to/bar.h"
         ^
path/to/foo.h:1:10: note: Consider adding deps = [ ":bar" ] to foo in path/to/BUILD.gn

Note that this clang plugin will be multimodal.
* When running locally, it will print the above message
* When running on RBE, it will print an error message requesting you to
  run a script to print suggestions (since it won't have access to
  headers.txt in the remote action).

Bug: b:500845363
Change-Id: Ie8ff5563163db00ac5a630c988ebd6356a6a6964